name: Deploy Terraform from Google Forms

on:
  push:
    paths:
      - "form-data.json"  # Trigger only when form-data.json is updated
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read

jobs:
  terraform:
    name: Deploy Azure Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Read Form Data
        run: cat form-data.json  # Verify input

      - name: Apply Terraform
        run: terraform apply -auto-approve

